version: 0.2

phases:
  pre_build:
    commands:
      - echo Install Docker
      - apk --no-cache update && apk add openrc --no-cache && apk --no-cache add docker
      - service docker stop
      - service docker start
      - which docker
      - echo Installing AWSCLI
      - apk --no-cache update && apk --no-cache add python py-pip py-setuptools ca-certificates groff less && pip --no-cache-dir install awscli && rm -rf /var/cache/apk/*
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
